### ISSUE TITLE
Mysterious caching of test code

### ISSUE THREAD

**Issue by MilesCranmer** [julia-vscode/TestItemRunner.jl#97]
So, I haven't been able to get a reliable MWE for this. I just noticed that sometimes (on both 1.10.6 and 1.11.1), I will:

1. Run a `@testitem` test in VSCode.
2. Observe the test to fail.
3. Modify the code and re-run the test.
4. Observe the test to fail.
5. Inspect the error, and realise that TestItemRunner.jl is **running some cached version of the code from before my edits.**

This happens even if I manually check, from shell, that the current test file is in fact correct (and I didn't forget to save it or something silly).

This is problematic behavior and I'm not really sure what to do. It seems like there's some weird sort of code caching mechanism going on in TestItemRunner.jl that isn't being handled in a totally robust way?

I also haven't really been able to figure out the pattern for when this occurs. When it does occur, I find sometimes a combination of re-editing the test with random edits, like print statements, or commenting out lines, will be enough to tell TestItemRunner.jl that it needs to update the code on the next run.

**Comment by davidanthoff** [comment]
So this is only in VS Code, right? And it only does _not_ pick up edits that are inside the `@testitem` macro block, not say an edit to the package you are editing?

The most likely reason is that something is going wrong with the language server... The LS is in charge of answering the question "what is the code in test item X". Are you seeing any crashes of the LS?

**Comment by MilesCranmer** [comment]
Yes, only in VSCode. If I run the test suite from the REPL, everything is fine.

And I am fairly confident that it is just edits to code within the `@testitem` block that don't get picked up, but code in the package do trigger correct re-tests. But I'm not 100% certain of this as the sample size is small.

I sometimes see the LS crash but in other contexts which seem to be unrelated.

**Comment by kenahoo** [comment]
I have seen this when I make edits to a test file, then click the VS Code run-test button *without clicking anywhere else first*.

I have auto-save set in VS Code, and it seems to kick off the test *before* it changes focus from the test code (which is what triggers saving the file).  I've now developed the habit of manually hitting Command-S before running a test, or even just clicking somewhere (anywhere) else before hitting the test button, and the problem is resolved.  Every once in a while I forget, and the symptom does reappear.

**Comment by MilesCranmer** [comment]
This issue is driving me a bit crazy. For me, even hitting command-S doesn't help it. Sometimes I even force quit and restart VSCode, and, same error.

is there some way I can forcefully flush the LanguageServer.jl cache or something? I don't care if it takes a bit longer to start, it's better than running the tests in my REPL.

**Comment by MilesCranmer** [comment]
Here's an example of what I mean –

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/4e071677-a7e7-403e-99a8-e0e20ac16c84" />

I forgot the import, so running the test hit an error. But when I add the import, the error still occurs as if it had completely cached the test and ignored my update.

Is something failing to communicate the tests to VSCode's test runner or something? Maybe VSCode is just unaware that there is new test code?

**Comment by MilesCranmer** [comment]
The really crazy thing is even if I change the test name:

<img width="669" alt="Image" src="https://github.com/user-attachments/assets/dacbecf7-c447-4a39-87c1-abc2e2b52f88" />

it **still** uses some cached code of the test. Even if I move the test to the bottom of the file!

I would have thought this would force the test runner to reload the code?

**Comment by MilesCranmer** [comment]
@davidanthoff is there some way I can see the code it's executing?

**Comment by davidanthoff** [comment]
I'm trying to fix this right now, but I'm having a hard time replicating it (I should say, it did happen to me as well at some point)...

One quick question: when you change the name of the test item, does the test tree view pick-up the new name? And then still run the old code?

**Comment by davidanthoff** [comment]
Another question: could you double check whether the LS process crashed and then restart (silently) when this happened? One explanation is that the LS process crashed, during that point any changes are no longer picked up, but the test stuff still allows you to run the old code.

**Comment by davidanthoff** [comment]
@MilesCranmer Ok, I have published a new prerelease of the extension v1.129 that fixes _one_ specific case of caching. I am kind of doubtful that it was the problem you ran into, though, because the problem I fixed is kind of hard to run into, I think... But could you still give it a try and see whether you are still seeing the same problem?

Also, just to confirm: all cases here are updates inside a `@testitem` that aren't picked up, correct? Not ever any code outside of the test item, say in the package itself that is being tested etc.

**Comment by MilesCranmer** [comment]
Sorry for the late reply. Thanks for your help on this.

> Another question: could you double check whether the LS process crashed and then restart (silently) when this happened?

Not sure if this answers your question, but I find that if I `pkill julia` (which I'm assuming also has the language server?), and re-run the test, that successfully seems to clear the cached test code.

> Also, just to confirm: all cases here are updates inside a `@testitem` that aren't picked up, correct? Not ever any code outside of the test item, say in the package itself that is being tested etc.

I think so. I'm trying to think of a case where updates to the package itself weren't propagated, but I don't think this has happened. I'm maybe 90% sure.

**Comment by davidanthoff** [comment]
@MilesCranmer just to follow up on this: are you still seeing this problem? I haven't run into it in a couple of weeks now.

**Comment by MilesCranmer** [comment]
Yeah I haven’t seen in a while either. Do we know why? Or, might it come back?

**Comment by davidanthoff** [comment]
I did make changes that might just have fixed this for good, so I'll close for now, but please reopen if you see it again.

**Comment by davidanthoff** [comment]
Yeah, this is definitely a different issue. I think this boils down to whether Revise can track these kind of changes...

**Comment by MilesCranmer** [comment]
Had something similar come up today again. This time it seems the test runner was stuck on a different version of the package than was in the environment. After doing `pkill julia` (which usually works as a fix) and updating the Manifest, it still didn't want to use the updated one. Is there a way I can see what Manifest is used by the test runner maybe?

**Comment by MilesCranmer** [comment]
I added `@show Pkg.status()` to my test and it prints this:

```
Status `/private/var/folders/1h/xyppkvx52cl6w3_h8bw_gdqh0000gr/T/jl_vvz73W/Project.toml`
  [4c88cf16] Aqua v0.8.11
⌃ [8ce10254] Bumper v0.6.0
  [34da2185] Compat v4.16.0
  [a0c0ee7d] DifferentiationInterface v0.6.39
  [8d63f2c5] DispatchDoctor v0.4.19
  [a40a106e] DynamicExpressions v1.9.4
  [06fc5a27] DynamicQuantities v1.4.0
  [7da242da] Enzyme v0.13.30
  [f6369f11] ForwardDiff v0.10.38
  [c3a54625] JET v0.9.17
  [0f8b85d8] JSON3 v1.14.1
  [d3d80556] LineSearches v7.3.0
  [e6f89c97] LoggingExtras v1.1.0
  [bdcacae8] LoopVectorization v0.12.171
  [a7f614a8] MLJBase v1.7.0
  [e80e1ace] MLJModelInterface v1.11.0
  [72560011] MLJTestInterface v0.2.8
⌅ [429524aa] Optim v1.10.0
  [1bc83da4] SafeTestsets v0.1.0
  [fd094767] Suppressor v0.2.8
⌃ [8254be44] SymbolicRegression v1.6.0
⌃ [d1185830] SymbolicUtils v3.13.0
  [899adc3e] TensorBoardLogger v0.1.25
  [f8b46487] TestItemRunner v1.1.0
  [1c621080] TestItems v1.0.0
⌃ [e88e6eb3] Zygote v0.6.75
  [8ba89e20] Distributed v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [44cfe95a] Pkg v1.11.0
  [9a3f8284] Random v1.11.0
  [f489334b] StyledStrings v1.11.0
  [8dfed614] Test v1.11.0
```

It says that SymbolicRegression.jl is v1.6.0 which is incorrect - it is currently v1.7.1. My root directory `Project.toml` is correctly versioned.


I then manually deleted `/private/var/folders/1h/xyppkvx52cl6w3_h8bw_gdqh0000gr/T/jl_vvz73W/Project.toml` and killed Julia and restarted the runner. But, again, it shows

```
⌃ [8254be44] SymbolicRegression v1.6.0
```

in the `Pkg.status()` within the runner. So, seemingly, it reloaded the same incorrect Project/Manifest from somewhere.

I did a search for any other `Manifest.toml` files, and it looks like `test/Manifest.toml` has an out-of-date SymbolicRegression.jl. So, I deleted `test/Manifest.toml` and restarted. Then, finally, it gives:

```
  [8254be44] SymbolicRegression v1.7.1 `~/PermaDocuments/SymbolicRegressionMonorepo/SymbolicRegression.jl`
```

Not sure what happened here.

Could it be something about me using TestEnv.jl locally that messes with the Manifest that the test runner uses? Or something else?

**Comment by MilesCranmer** [comment]
This seems to be an issue again. Could we re-open this @davidanthoff?

Like last time I find it hard to get a deterministic reproducer, but I definitely see this once in a while.

**Comment by MilesCranmer** [comment]
It seems to be related to changing code inside a macro. It seems that the library does not get reloaded when this happens. So my temporary workaround is to comment out the use of the macro, re-run the test, then put the code back.
